default: &default
  adapter: postgresql
  encoding: unicode
  database: moosehead
  username: moosehead
  password: password
  port: 5433
  pool: 5

development:
  <<: *default
  database: moosehead_development

test:
  <<: *default
  database: moosehead_test

production:
  <<: *default
  database: moosehead_production
  username: moosehead
  password: <%= ENV['MOOSEHEAD_DATABASE_PASSWORD'] %>
